CREATE DATABASE IF NOT EXISTS shshare;
USE shshare;

CREATE TABLE IF NOT EXISTS ticket(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
    name VARCHAR(255),
    email VARCHAR(256),
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);