CREATE DATABASE IF NOT EXISTS shshare;
USE shshare;

CREATE TABLE IF NOT EXISTS ticket(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
    name VARCHAR(255),
    email VARCHAR(256),
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
    name VARCHAR(255),
    email VARCHAR(256),
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS roles(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS user_roles(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
    roles_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY (roles_id)
        REFERENCES roles(id)
        ON DELETE CASCADE,
    FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX user_email ON users (email);

INSERT INTO roles (name) VALUES ('user');
INSERT INTO roles (name) VALUES ('moderator');
INSERT INTO roles (name) VALUES ('admin');